#!/usr/bin/python3.8

import sys,glob
from pathlib import Path
sys.path.append("/home/gauenk/Documents/experiments/cl_gen/lib/")
from explore.io.uuid_cache import get_config_from_uuid_list
from explore.io.utils import print_formatted_exp_info

def create_uuid_list_from_glob(path_l):
    uuid_l = []
    for filename in path_l:
        uuid_l.append(str(Path(filename).stem))
    return uuid_l

if len(sys.argv) == 1:
    print("lsc allows users to quickly read cache info.")
    exit()

path_l = sys.argv[1:]
uuid_l = create_uuid_list_from_glob(path_l)
config_l = get_config_from_uuid_list(uuid_l)

# -- print results --
for path,uuid,config in zip(path_l,uuid_l,config_l):
    if config != -1:
        print("-="*35)
        print(f"Path: {path}")
        print(f"\tUUID: {uuid}")
        print_formatted_exp_info(config,indent=8)
